FROM oven/bun:1.1
RUN groupadd -r bunapi && useradd -r -g bunapi bunapi
USER bunapi
WORKDIR /api/
COPY --chown=bunapi package*.json ./
COPY --chown=bunapi bun.lockb ./
COPY --chown=bunapi . .
RUN bun install
EXPOSE 3000
CMD ["bun", "run", "bun:dev"]
