services:
  db:
    container_name: cont_db_api
    image: postgres:14.13-alpine3.20
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: jgezziel
      POSTGRES_PASSWORD: 635jgezziel131
      POSTGRES_DB: api_db
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - net_api
  pgadmin:
    image: dpage/pgadmin4
    container_name: cont_pgadmin_api
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: jgezziel@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 635jgezziel131
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - ./pgAdmin/servers.json:/pgadmin4/servers.json
    networks:
      - net_api
  api:
    depends_on:
      - db
    container_name: cont_api_node
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/api
      - /api/node_modules
    restart: unless-stopped
    networks:
      - net_api
volumes:
  pgdata:
  pgAdmin:
networks:
  net_api:
